# Generated by Django 4.2.6 on 2023-11-08 11:21

import django.core.files.storage
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_options_remove_content_ordering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='picture',
            field=stdimage.models.StdImageField(force_min_size=False, help_text='Рекомендуемый размер 1x1', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='genre_pictures/', variations={'large': (1080, 1080), 'medium': (768, 768), 'small': (200, 200), 'thumb': (75, 75)}, verbose_name='Картинка'),
        ),
    ]
